api_app/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url, include
from rest_framework import routers
from api_app.views import SupervisorCampanasActivasViewSet

router = routers.DefaultRouter()
router.register(
    r'api/v1/supervisor/campanas', SupervisorCampanasActivasViewSet,
    base_name='supervisor_campanas')

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

ominicontacto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.i18n import javascript_catalog

js_info_dict = {
    'packages': ('ominicontacto_app',),
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ominicontacto_app.urls')),
    url(r'^', include('reciclado_app.urls')),
    url(r'^', include('reportes_app.urls')),
    url(r'^', include('configuracion_telefonia_app.urls')),
    url(r'^', include('api_app.urls')),
    url(r'^accounts/logout/$', auth_views.logout,
        {'next_page': '/accounts/login/'}, name="logout"),

]

urlpatterns += [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
]

ominicontacto_app/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

from django.conf import settings
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib.auth.decorators import login_required

from ominicontacto_app import (
    views, views_base_de_datos_contacto, views_contacto, views_campana_creacion,
    views_grabacion, views_calificacion, views_formulario, views_agente,
    views_calificacion_cliente, views_campana, views_campana_reportes, views_pdf,
    views_agenda_contacto, views_campana_dialer_creacion, views_campana_dialer,
    views_back_list, views_sitio_externo, views_queue_member, views_user_api_crm,
    views_campana_dialer_template, views_campana_manual_creacion, views_campana_manual,
    views_campana_preview, views_archivo_de_audio, views_user_profiles,
)

from ominicontacto_app.views_utils import (
    handler400, handler403, handler404, handler500
)

from ominicontacto_app.auth.decorators import (
    administrador_requerido, administrador_o_supervisor_requerido, agente_requerido,
    permiso_administracion_requerido, supervisor_requerido)

handler400 = handler400
handler403 = handler403
handler404 = handler404
handler500 = handler500


urlpatterns = [
    url(r'^admin/defender/', include('defender.urls')),  # defender admin
    url(r'^ajax/mensaje_recibidos/',
        views.mensajes_recibidos_view,
        name='ajax_mensaje_recibidos'),
    url(r'^$', views.index_view, name='index'),

    # ==========================================================================
    # Usuarios y Perfiles
    # ==========================================================================
    url(r'^accounts/login/$', views.login_view, name='login'),
    url(r'^user/nuevo/$',
        administrador_o_supervisor_requerido(views_user_profiles.CustomUserWizard.as_view()),
        name='user_nuevo',
        ),
    url(r'^user/list/page(?P<page>[0-9]+)/$',
        administrador_o_supervisor_requerido(views_user_profiles.UserListView.as_view()),
        name='user_list'
        ),
    url(r'^user/delete/(?P<pk>\d+)/$',
        administrador_o_supervisor_requerido(views_user_profiles.UserDeleteView.as_view()),
        name='user_delete',
        ),
    url(r'^user/update/(?P<pk>\d+)/$',
        administrador_o_supervisor_requerido(views_user_profiles.CustomerUserUpdateView.as_view()),
        name='user_update',
        ),
    # Perfil Agente  ==========================================================
    url(r'^agente/list/$',
        administrador_o_supervisor_requerido(views_user_profiles.AgenteListView.as_view()),
        name='agente_list',
        ),
    url(r'^user/agenteprofile/update/(?P<pk_agenteprofile>\d+)/$',
        administrador_requerido(views_user_profiles.AgenteProfileUpdateView.as_view()),
        name='agenteprofile_update',
        ),
    # Perfil Supervisor  =======================================================
    url(r'^supervisor/list/$',
        administrador_requerido(views_user_profiles.SupervisorListView.as_view()),
        name='supervisor_list',
        ),
    url(r'^supervisor/(?P<pk>\d+)/update/$',
        administrador_requerido(views_user_profiles.SupervisorProfileUpdateView.as_view()),
        name='supervisor_update',
        ),
    # ==========================================================================
    # Módulos
    # ==========================================================================
    url(r'^modulo/nuevo/$',
        administrador_requerido(views.ModuloCreateView.as_view()), name='modulo_nuevo',
        ),
    url(r'^modulo/update/(?P<pk>\d+)/$',
        administrador_requerido(views.ModuloUpdateView.as_view()),
        name='modulo_update',
        ),
    url(r'^modulo/list/$',
        administrador_requerido(views.ModuloListView.as_view()), name='modulo_list',
        ),
    url(r'^modulo/delete/(?P<pk>\d+)/$',
        administrador_requerido(views.ModuloDeleteView.as_view()),
        name='modulo_delete',
        ),
    # ==========================================================================
    # Grupos
    # ==========================================================================
    url(r'^grupo/list/$',
        administrador_o_supervisor_requerido(views.GrupoListView.as_view()), name='grupo_list',
        ),
    url(r'^grupo/nuevo/$',
        administrador_o_supervisor_requerido(views.GrupoCreateView.as_view()), name='grupo_nuevo',
        ),
    url(r'^grupo/update/(?P<pk>\d+)/$',
        administrador_o_supervisor_requerido(views.GrupoUpdateView.as_view()),
        name='grupo_update',
        ),
    url(r'^grupo/delete/(?P<pk>\d+)/$',
        administrador_o_supervisor_requerido(views.GrupoDeleteView.as_view()),
        name='grupo_delete',
        ),
    # ==========================================================================
    # Pausas
    # ==========================================================================
    url(r'^pausa/list/$',
        administrador_o_supervisor_requerido(views.PausaListView.as_view()),
        name='pausa_list',
        ),
    url(r'^pausa/nuevo/$',
        administrador_o_supervisor_requerido(views.PausaCreateView.as_view()),
        name='pausa_nuevo',
        ),
    url(r'^pausa/update/(?P<pk>\d+)/$',
        administrador_o_supervisor_requerido(views.PausaUpdateView.as_view()),
        name='pausa_update',
        ),
    url(r'^pausa/delete/(?P<pk>\d+)/$',
        administrador_o_supervisor_requerido(views.PausaToggleDeleteView.as_view()),
        name='pausa_delete',
        ),

    url(r'^node/$', login_required(views.node_view), name='view_node'),

    url(r'^smsThread/$',
        login_required(views.mensajes_recibidos_enviado_remitente_view),
        name='view_sms_thread'),
    url(r'^sms/getAll/$',
        login_required(views.mensajes_recibidos_view),
        name='view_sms_get_all'),
    url(r'^blanco/$',
        login_required(views.blanco_view),
        name='view_blanco'),

    # ==========================================================================
    # Grabaciones
    # ==========================================================================
    url(r'^node/grabacion/marcar/$',
        login_required(views_grabacion.MarcarGrabacionView.as_view()),
        name='grabacion_marcar',
        ),
    url(r'^grabacion/descripcion/(?P<uid>[\d .]+)/$',
        login_required(views_grabacion.GrabacionDescripcionView.as_view()),
        name='grabacion_descripcion',
        ),
    url(r'^grabacion/buscar/(?P<pagina>\d+)/$',
        permiso_administracion_requerido(views_grabacion.BusquedaGrabacionFormView.as_view()),
        name='grabacion_buscar',
        ),

    url(r'^agenda/nuevo/$',
        agente_requerido(views.nuevo_evento_agenda_view),
        name='agenda_nuevo',
        ),
    url(r'^agenda/agente_list/$',
        agente_requerido(views.AgenteEventosFormView.as_view()),
        name='agenda_agente_list',
        ),
    url(r'^duracion/llamada/$',
        login_required(views.nuevo_duracion_llamada_view),
        name='nueva_duracion_llamada',
        ),
    url(r'^chat/mensaje/$',
        login_required(views.mensaje_chat_view),
        name='nueva_mensaje_chat',
        ),
    url(r'^chat/create/$',
        login_required(views.crear_chat_view),
        name='chat_create',
        ),
    url(r'^supervision_externa/$',
        supervisor_requerido(views.supervision_url_externa),
        name='supervision_externa_url',
        ),
    url(r'^acerca/$',
        login_required(views.AcercaTemplateView.as_view()),
        name='acerca',
        ),
    # ==========================================================================
    # Servicios para phoneJS
    # ==========================================================================
    url(r'^service/campana/activas/$',
        login_required(
            views_agente.CampanasActivasView.as_view()),
        name="service_campanas_activas"),
    url(r'^service/agente/otros_agentes_de_grupo/$',
        login_required(
            views_agente.AgentesDeGrupoPropioView.as_view()),
        name="service_agentes_de_grupo"),
    # ==========================================================================
    # Base Datos Contacto
    # ==========================================================================
    url(r'^base_datos_contacto/$',
        administrador_o_supervisor_requerido(
            views_base_de_datos_contacto.BaseDatosContactoListView.as_view()),
        name='lista_base_datos_contacto',
        ),
    url(r'^base_datos_contacto/nueva/$',
        administrador_o_supervisor_requerido(
            views_base_de_datos_contacto.BaseDatosContactoCreateView.as_view()),
        name='nueva_base_datos_contacto'
        ),
    url(r'^base_datos_contacto/(?P<pk_bd_contacto>\d+)/actualizar/$',
        administrador_o_supervisor_requerido(
            views_base_de_datos_contacto.BaseDatosContactoUpdateView.as_view()),
        name='update_base_datos_contacto'
        ),
    # TODO: Verificar que esta vista se use
    url(r'^base_datos_contacto/(?P<pk>\d+)/validacion/$',
        administrador_o_supervisor_requerido(
            views_base_de_datos_contacto.DefineBaseDatosContactoView.as_view()),
        name='define_base_datos_contacto',
        ),
    url(r'^base_datos_contacto/(?P<bd_contacto>\d+)/agregar/$',

reportes_app/forms.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
from __future__ import unicode_literals

import json

from django.utils.translation import ugettext as _
from django import forms

from ominicontacto_app.utiles import convert_fecha_datetime


EMPTY_CHOICE = ('', '---------')


class ReporteAgentesForm(forms.Form):
    """
    El form para reporte con fecha
    """
    fecha = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    agente = forms.MultipleChoiceField(required=False, choices=())
    grupo_agente = forms.ChoiceField(required=False, choices=(), widget=forms.Select(
        attrs={'class': 'form-control'}))
    todos_agentes = forms.BooleanField(required=False)

    def __init__(self, agentes_asociados, grupos_asociados, *args, **kwargs):
        super(ReporteAgentesForm, self).__init__(*args, **kwargs)

        agente_choice = [(agente.pk, agente.user.get_full_name())
                         for agente in agentes_asociados]
        self.fields['agente'].choices = agente_choice
        grupo_choice = [(grupo.id, grupo.nombre)
                        for grupo in grupos_asociados]
        grupo_choice.insert(0, EMPTY_CHOICE)
        self.fields['grupo_agente'].choices = grupo_choice


class ReporteLlamadasForm(forms.Form):
    """
    El form para reporte de llamadas
    """
    fecha = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    finalizadas = forms.BooleanField(required=False, label=_(u'Incluir campañas finalizadas'))

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')
        try:
            fecha_desde, fecha_hasta = fecha.split('-')
            fecha_desde = convert_fecha_datetime(fecha_desde)
            fecha_hasta = convert_fecha_datetime(fecha_hasta, final_dia=True)
        except ValueError:
            raise forms.ValidationError(_('Formato inválido'))
        self.desde = fecha_desde
        self.hasta = fecha_hasta
        return fecha


class EstadisticasJSONForm(forms.Form):
    estadisticas = forms.CharField()

    def clean_estadisticas(self):
        estadisticas = self.cleaned_data.get('estadisticas')
        try:
            json_data = json.loads(estadisticas)
        except ValueError:
            raise forms.ValidationError(_(u'Formato JSON invalido'))
        return json_data


TIPO_REPORTE_CHOICES = (
    ('llamadas_por_tipo', ''),
    ('llamadas_por_campana', ''),
    ('tipos_de_llamada_manual', ''),
    ('tipos_de_llamada_dialer', ''),
    ('tipos_de_llamada_entrante', ''),
    ('tipos_de_llamada_preview', ''),
)


class ExportarReporteLlamadasForm(EstadisticasJSONForm):
    tipo_reporte = forms.ChoiceField(choices=TIPO_REPORTE_CHOICES, required=True)

ominicontacto_app/templates/base_create_update_form.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<div>
    <form action = "" method = "post">
        {% include "base_form_fields.html" with form=form %}
        <hr>
        <button type="submit" id="id_registrar" class="btn btn-primary">
            {% trans 'Guardar' %}
        </button>
    </form>

</div>

{% endblock %}

ominicontacto_app/templates/blanco.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <title>{% trans 'Title' %}</title>
</head>
<body>

</body>
</html>

ominicontacto_app/templates/busqueda_grabacion.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block head_js %}
<script type="text/javascript">
 $(function() {
   var start = moment().subtract(29, 'days');
   var end = moment();
   function cb(start, end) {
     $('#id_fecha').html(start.format('DD/MM/YYYY') + ' - ' + end.format('DD/MM/YYYY'));
   }

   $('#id_fecha').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
  });

   $('#id_fecha').on('cancel.daterangepicker', function(ev, picker) {
     $(this).val('');
   });

   var ranges = get_ranges();

   // Init daterange plugin
   $('#id_fecha').daterangepicker(
     {
       locale: {
         format: 'DD/MM/YYYY'
       },
       autoUpdateInput: false,
       ranges: ranges,
     }, cb);

   cb(start, end);

 });

 function filtrar_pagina(pagina) {
   $("#id_pagina").val(pagina);
   $("#form-buscar-grabacion").submit();
 };
</script>

{% endblock %}
{% block content %}

<h1>{% trans 'Buscar grabación' %}</h1>

<div id="wrapper-search">
    <button id="btnCollapse" class="btn btn-block" type="button" data-toggle="collapse" data-target="#wrapperSearchForm" aria-expanded="true" aria-controls="wrapperSearchForm"><span class="icon icon-search"></span> {% trans 'Buscar' %}</button>
    <div id="wrapperSearchForm" class="show">
        <form id="form-buscar-grabacion" role="form" method="post" enctype="multipart/form-data" >
            {% include "base_form_fields.html" with form=form %}
            <button type="submit" id="id_buscar_btn" class="btn btn-primary">
                {% trans 'Buscar' %}
            </button>
        </form>
    </div>
</div>

<div class="wrapper-results">
    <table class="table table-stripped">
        <thead>
            <tr>
                <th>{% trans 'Fecha' %}</th>
                <th>{% trans 'Tipo de llamada' %}</th>
                <th>{% trans 'tel_cliente' %}</th>
                <th>{% trans 'Agente' %}</th>
                <th>{% trans 'Campaña' %}</th>
                <th>{% trans 'Grabación' %}</th>
                <th>{% trans 'Descripción' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for grabacion in listado_de_grabaciones %}
            <tr>
                <td>{{ grabacion.fecha|date:"Y-m-d H:i"}}</td>
                <td>{{ grabacion.get_tipo_llamada_display}}</td>
                <td>{{ grabacion.tel_cliente}}</td>
                <td>{{ grabacion.agente}}</td>
                <td>{{ grabacion.campana}}</td>
                <td>
                    <audio controls>
                        <source src="{{ grabacion.url }}" type='audio/mpeg'>
                            {% trans 'Escuchar' %}
                    </audio>
                    <a href="{{ grabacion.url }}" target="_blank">
                        <span class="glyphicon glyphicon-download-alt" aria-hidden="true" title="{% trans 'Descargar' %}"></span>
                    </a>
                </td>
                <td><button type="button" class="btn btn-light btn-sm" data-toggle="modal"
                            data-target="#descripcionModal" data-uid="{{ grabacion.uid }}">{% trans 'Descripción' %}</button></td>
            </tr>
       {% empty %}
        <tr>
            <td colspan="7">{% trans 'No existen grabaciones' %}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination">
        {% if listado_de_grabaciones.has_previous %}
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Previous" onclick="javascript:filtrar_pagina({{listado_de_grabaciones.previous_page_number}})">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">{% trans 'Anterior' %}</span>
              </a>
            </li>
        {% endif %}
        {% for page in listado_de_grabaciones.paginator.page_range %}
            <li class="page-item {% if listado_de_grabaciones.number == page  %}active{% endif %}"><a class="page-link" href="#" onclick="javascript:filtrar_pagina({{page}})">{{ page }}</a></li>
        {% endfor %}

        {% if listado_de_grabaciones.has_next %}
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next" onclick="javascript:filtrar_pagina({{listado_de_grabaciones.next_page_number}})">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">{% trans 'Siguiente' %}</span>
              </a>
            </li>
        {% endif %}
        </ul>
    </nav>

 <div class="modal fade" id="descripcionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
     <div class="modal-dialog" role="document">
         <div class="modal-content">
             <div class="modal-header">
                <h1 class="modal-title" id="descripcionModalLabel"></h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             </div>
             <div class="modal-body">
                 <form>
                     <div class="description-text" id="descripcion-text">
                     </div>
                 </form>
             </div>
             <div class="modal-footer">
                 <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cerrar' %}</button>
             </div>
         </div>
     </div>
 </div>
</div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'ominicontacto/CSS/select2.min.css' %}"></link>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'ominicontacto/JS/select2.min.js' %}"></script>
    <script>
     /* se activa en todos los campos de selección un plugin para
        JQuery que permite una mejor búsqueda */
     $(document).ready(function() {

       $('select.form-control').each(function() {
         $(this).select2();});


       /* $('#id_campana').attr('class', 'select2-hidden-accessible');*/

       $('#descripcionModal').on('show.bs.modal', function (event) {
         var button = $(event.relatedTarget)
         var uid_val = button.data('uid');
         var modal = $(this);
         var URL = "/grabacion/descripcion/" + uid_val + "/";
         $.get( URL, function( data ) {
           $('#descripcionModalLabel').text(data.result);
           $('#descripcion-text').text(data.descripcion);
           console.log(data);
         })
          .fail(function( data ){
            $('#descripcionModalLabel').text("{% trans 'Error' %}");
            $('#descripcion-text').text("{% trans 'Ha ocurrido un error al intentar conectarse' %}");
            console.log(data);
          });
       });
       });
    </script>
{% endblock %}

ominicontacto_app/templates/delete_grupo.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div>
    <form method="post">{% csrf_token %}
        <h1>{% blocktrans %}Grupo "{{ object.nombre}}" {% endblocktrans %}</h1>
        <p>{% trans '¿Está seguro que desea eliminar este grupo?' %}</p>
        <button type="submit" class="btn btn-danger">{% trans 'Eliminar' %}</button>
        <a class="btn btn-outline-danger" href="{% url 'grupo_list' %}">{% trans 'Cancelar' %}</a>
    </form>
</div>
{% endblock %}

ominicontacto_app/templates/delete_pausa.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div>
    <form method="post">{% csrf_token %}
        <h1>{% blocktrans %}Pausa "{{ object.nombre}}" {% endblocktrans %}</h1>
        {% if object.eliminada %}
           <p>{% trans '¿Desea reactivar esta Pausa?' %}</p>
        {% else %}
           <p>{% trans '¿Está seguro que desea eliminar esta Pausa?' %}</p>
        {% endif %}
        <button type="submit" class="btn btn-danger">
        {% if object.eliminada %}
            {% trans 'Reactivar' %}
        {% else %}
            {% trans 'Eliminar' %}
        {% endif %}
        </button>
        <a class="btn btn-outline-danger" href="{% url 'pausa_list' %}">{% trans 'Cancelar' %}</a>
    </form>
</div>
{% endblock %}

ominicontacto_app/templates/index.html
<!--
Copyright (C) 2018 Freetech Solutions

This file is part of OMniLeads

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

-->
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
<div id="crm" class="crm"></div>
<!--    <p>hola {{ user.first_name }} {{ user.last_name }} {{ user.username }}</p>
    <p>{{ user.get_agente_profile.sip_extension }}</p>
    <p>{{ user.get_agente_profile.sip_password }}</p>-->


{% endblock %}
{% block logueo %}
<div class="wrapper-content welcome">
        <h1>{% trans 'Bienvenidos a Omnileads' %}</h1>
	<h3>{% trans 'Debe loguearse para operar con nuestro sistema' %}</h3>
	<br>
	<div>
	    <a class="btn btn-primary" role="button" href="{% url 'login' %}">{% trans 'Ingresar' %}</a>
	</div>
	<div>
	    <a class="btn btn-outline-primary" role="button" href="/static/ominicontacto/voip.cert" target="_blank">{% trans 'bajar certificado digital' %}</span></a>
	</div>
	</div>
{% endblock %}